<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="API Suite" duration-ms="77132" started-at="2020-02-11T18:45:09 EST" finished-at="2020-02-11T18:46:26 EST">
    <groups>
    </groups>
    <test name="Test on Rest API " duration-ms="77132" started-at="2020-02-11T18:45:09 EST" finished-at="2020-02-11T18:46:26 EST">
      <class name="EBApparel_Tests.Functional_tests">
        <test-method status="PASS" signature="setup()[pri:0, instance:EBApparel_Tests.Functional_tests@589838eb]" name="setup" is-config="true" duration-ms="73025" started-at="2020-02-11T18:45:09 EST" finished-at="2020-02-11T18:46:22 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="searchtest()[pri:0, instance:EBApparel_Tests.Functional_tests@589838eb]" name="searchtest" duration-ms="3782" started-at="2020-02-11T18:46:22 EST" finished-at="2020-02-11T18:46:26 EST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Found 954 items for your search of PS4.] but found [Found 959 items for your search of PS4.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Found 954 items for your search of PS4.] but found [Found 959 items for your search of PS4.]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at EBApparel_Tests.Functional_tests.searchtest(Functional_tests.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$284/977670022.accept(Unknown Source)
at java.util.ArrayList.forEach(ArrayList.java:1234)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at org.testng.internal.thread.ThreadUtil$$Lambda$37/101478235.call(Unknown Source)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchtest -->
      </class> <!-- EBApparel_Tests.Functional_tests -->
    </test> <!-- Test on Rest API  -->
  </suite> <!-- API Suite -->
</testng-results>
